### ISSUE TITLE
GraphqlError: Resource not accessible by integration 

### ISSUE THREAD

**Issue by alex-page** [alex-page/add-new-issue-project#5]
@TheSalesOpsGuy is having some problems with the GraphQl resource. I will need to investigate what is going on!

```
✖  fatal     GraphqlError: Resource not accessible by integration 
    at request.then.response (/node_modules/@octokit/graphql/lib/graphql.js:31:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

https://github.com/alex-page/add-new-issue-project/issues/3#issuecomment-485497977

**Comment by alex-page** [comment]
@TheSalesOpsGuy I did a solid investigation on this and I am lost as to why this error would be occurring.

1. Is there anything unique about the way the action is being triggered or how the project board is set up? 
1. Can you provide any additional information around the repo and project board you are doing this for( private repo, private board, organisation board)?
1. Are you able to share with me your current set up?

**Comment by TheSalesOpsGuy** [comment]
@alex-page thanks for looking into this for me, the `automagic issue to project` is a super desired feature from my POV

> Is there anything unique about the way the action is being triggered or how the project board is set up?

I don't think so, literally the only thing in the main.workflow file is your flow:
![image](https://user-images.githubusercontent.com/35553190/56607965-9638b080-65be-11e9-9e28-aabac18c9c6e.png)

The project board is just a standard one under `Projects`

> Can you provide any additional information around the repo and project board you are doing this for( private repo, private board, organisation board)?

sure, it's a private repo and a private repo level board, anything else useful to know?

> Are you able to share with me your current set up?

Not 💯 on what you are looking for here, happy to share (I think 😉) but not sure what you want

**Comment by alex-page** [comment]
I will make a mock repo with those settings and a public board, let me see if I can replicate the issue.

**Comment by alex-page** [comment]
I have invited you to a repo: https://github.com/alex-page/thesalesopguy/invitations

Adding new issues goes into the green column, feel free to add more issues. I am not sure if there is something different between the two set ups.

**Comment by TheSalesOpsGuy** [comment]
just jumped in and I see it working...

the workflow file is SLIGHTLY different so I'm going to copy ove the one in the new repo to mine to see if I get it moving

**Comment by alex-page** [comment]
Let me know if you have any problems. I am also going to publish it on GitHub actions marketplace as it might be only working in my own repositories.

**Comment by TheSalesOpsGuy** [comment]
No success but different error 😛 

With **this** file:
![image](https://user-images.githubusercontent.com/35553190/56610363-1d3c5780-65c4-11e9-94c5-f11d4e4fa732.png)

I get this error log
```
### STARTED Add new issues to project 19:31:19Z

Pulling image: gcr.io/github-actions-images/action-runner:latest
latest: Pulling from github-actions-images/action-runner
169185f82c45: Pulling fs layer
0ccde4b6b241: Pulling fs layer
d0372f57daa2: Pulling fs layer
165911d108d6: Pulling fs layer
54996bce1de5: Pulling fs layer
165911d108d6: Waiting
54996bce1de5: Waiting
0ccde4b6b241: Verifying Checksum
0ccde4b6b241: Download complete
d0372f57daa2: Verifying Checksum
d0372f57daa2: Download complete
169185f82c45: Verifying Checksum
169185f82c45: Download complete
165911d108d6: Verifying Checksum
165911d108d6: Download complete
54996bce1de5: Verifying Checksum
54996bce1de5: Download complete
169185f82c45: Pull complete
0ccde4b6b241: Pull complete
d0372f57daa2: Pull complete
165911d108d6: Pull complete
54996bce1de5: Pull complete
Digest: sha256:c9bb432ec5ec08ee08b040a9fccacebbbf8a91444dac4721600cf5dca9dae57e
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
Step 1/12 : FROM node:alpine
alpine: Pulling from library/node
Digest: sha256:15b5debfabe1df626e84e160fad14d3da8716562a45b4e1e4b5e1189a3d3497a
Status: Downloaded newer image for node:alpine
 ---> cd4fae427afc
Step 2/12 : LABEL "com.github.actions.name"="Add new issues to project"
 ---> Running in fe9c633204e8
 ---> 59fe8974b5bb
Step 3/12 : LABEL "com.github.actions.description"="✨ Magically add new issues to projects"
 ---> Running in b735d918194a
 ---> e8300499bd22
Step 4/12 : LABEL "com.github.actions.icon"="plus"
 ---> Running in 39a7b160b8ce
 ---> c803f41ae93b
Step 5/12 : LABEL "com.github.actions.color"="green"
 ---> Running in 7ce7fbde167e
 ---> 7cd207377fd2
Step 6/12 : LABEL "repository"="https://github.com/alex-page/add-new-issue-project"
 ---> Running in 88826131451c
 ---> f563c861f5b1
Step 7/12 : LABEL "homepage"="https://github.com/alex-page/add-new-issue-project"
 ---> Running in 184df2c6b5d4
 ---> fd1ea3676405
Step 8/12 : LABEL "maintainer"="Alex Page <alex@alexpage.com.au>".
 ---> Running in 780120a4fd36
 ---> 81f83e1d8399
Step 9/12 : COPY package*.json ./
 ---> 568adfa8a90e
Step 10/12 : RUN npm ci
 ---> Running in 96a8998e042c
added 87 packages in 2.083s
 ---> e16aa92b40a2
Step 11/12 : COPY . .
 ---> 803659630eb5
Step 12/12 : ENTRYPOINT ["node", "/index.js"]
 ---> Running in f953cad0da25
 ---> 9b9c3d63a450
Successfully built 9b9c3d63a450
Successfully tagged gcr.io/gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:947726dd6318753268f3bfbe5e87ae2afe220db399c26e119c181a59227b0c60
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
ℹ  info      Event closed is not supported by this action.

### DECLINED Add new issues to project 19:31:35Z (15.991s)```

**Comment by alex-page** [comment]
So that sounds correct if you closed an issue you should see this. We don't want this action to run when an issue is closed. GitHub actions currently run on high level events like `issues` so it will run for all issue events `closed`, `opened`, `assigned`, you can [find out more here](https://developer.github.com/actions/managing-workflows/workflow-configuration-options/#events-supported-in-workflow-files).

So that is just saying that an issue event happened, the event was closed and we do not want to do anything with that so we log an information saying `Event closed is not supported by this action.` If the event was `open` it should move the issue to the correct column.

Can you try opening an issue and checking the action panel, you should get a passing action and the issue should move to the chosen column 🙏

**Comment by TheSalesOpsGuy** [comment]
back to the old error 😢 
```
### STARTED Add new issues to project 19:43:59Z

Pulling image: gcr.io/github-actions-images/action-runner:latest
latest: Pulling from github-actions-images/action-runner
169185f82c45: Pulling fs layer
0ccde4b6b241: Pulling fs layer
d0372f57daa2: Pulling fs layer
165911d108d6: Pulling fs layer
54996bce1de5: Pulling fs layer
165911d108d6: Waiting
54996bce1de5: Waiting
d0372f57daa2: Verifying Checksum
d0372f57daa2: Download complete
0ccde4b6b241: Download complete
169185f82c45: Verifying Checksum
169185f82c45: Download complete
165911d108d6: Verifying Checksum
165911d108d6: Download complete
54996bce1de5: Verifying Checksum
54996bce1de5: Download complete
169185f82c45: Pull complete
0ccde4b6b241: Pull complete
d0372f57daa2: Pull complete
165911d108d6: Pull complete
54996bce1de5: Pull complete
Digest: sha256:c9bb432ec5ec08ee08b040a9fccacebbbf8a91444dac4721600cf5dca9dae57e
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
947726dd6318753268f3bfbe5e87ae2afe220db399c26e119c181a59227b0c60: Pulling from gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1
bdf0201b3a05: Already exists
f82315922d4f: Already exists
e70c14082adc: Already exists
90a12d6cded2: Pulling fs layer
6cdc961d2b82: Pulling fs layer
a001f4263443: Pulling fs layer
a001f4263443: Verifying Checksum
a001f4263443: Download complete
6cdc961d2b82: Verifying Checksum
6cdc961d2b82: Download complete
90a12d6cded2: Verifying Checksum
90a12d6cded2: Download complete
90a12d6cded2: Pull complete
6cdc961d2b82: Pull complete
a001f4263443: Pull complete
Digest: sha256:1629c81cfbfdf2309a32cb1841baba15a28716eb4f46bb5c0ec76270b55dd14e
Status: Downloaded newer image for gcr.io/gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:947726dd6318753268f3bfbe5e87ae2afe220db399c26e119c181a59227b0c60
Step 1/12 : FROM node:alpine
alpine: Pulling from library/node
Digest: sha256:15b5debfabe1df626e84e160fad14d3da8716562a45b4e1e4b5e1189a3d3497a
Status: Downloaded newer image for node:alpine
 ---> cd4fae427afc
Step 2/12 : LABEL "com.github.actions.name"="Add new issues to project"
 ---> Using cache
 ---> 57a028da276c
Step 3/12 : LABEL "com.github.actions.description"="✨ Magically add new issues to projects"
 ---> Using cache
 ---> 2785250d49cb
Step 4/12 : LABEL "com.github.actions.icon"="plus"
 ---> Using cache
 ---> 9b5d15042d5e
Step 5/12 : LABEL "com.github.actions.color"="green"
 ---> Using cache
 ---> 01b67d03cc6d
Step 6/12 : LABEL "repository"="https://github.com/alex-page/add-new-issue-project"
 ---> Using cache
 ---> 902754a0be5f
Step 7/12 : LABEL "homepage"="https://github.com/alex-page/add-new-issue-project"
 ---> Using cache
 ---> f4d41d418cb4
Step 8/12 : LABEL "maintainer"="Alex Page <alex@alexpage.com.au>".
 ---> Using cache
 ---> ec4a5c8c4fd9
Step 9/12 : COPY package*.json ./
 ---> Using cache
 ---> 1113e07b70e3
Step 10/12 : RUN npm ci
 ---> Using cache
 ---> 91bf62f074f9
Step 11/12 : COPY . .
 ---> Using cache
 ---> 5676281093b7
Step 12/12 : ENTRYPOINT ["node", "/index.js"]
 ---> Using cache
 ---> 9b9c3d63a450
Successfully built 9b9c3d63a450
Successfully tagged gcr.io/gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:947726dd6318753268f3bfbe5e87ae2afe220db399c26e119c181a59227b0c60
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
✖  fatal     GraphqlError: Resource not accessible by integration 
    at request.then.response (/node_modules/@octokit/graphql/lib/graphql.js:31:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

### FAILED Add new issues to project 19:44:10Z (10.736s)```

**Comment by alex-page** [comment]
@TheSalesOpsGuy thanks mate, i'll see if I have something configured in an odd way. It might take me a few days sorry for the wait!

**Comment by TheSalesOpsGuy** [comment]
No worries at all on the wait, you are helping me get further along than I was able to alone
༼ つ ◕ᴗ◕ ༽つ 🥞

**Comment by alex-page** [comment]
@TheSalesOpsGuy I have published the action on the marketplace now, maybe you can add it your project clicking the button on the repo page. It might be happier or nothing might change 🤔

**Comment by TheSalesOpsGuy** [comment]
ok trying now, will let you know

small typo on your marketplace listing, this should be `repo` I think
![image](https://user-images.githubusercontent.com/35553190/56615231-85dd0180-65cf-11e9-8325-f031d2ed7db7.png)

**Comment by TheSalesOpsGuy** [comment]
it certainly seems like the same thing is happening.
```
Step 12/12 : ENTRYPOINT ["node", "/index.js"]
 ---> Using cache
 ---> bd77dab587ce
Successfully built bd77dab587ce
Successfully tagged gcr.io/gct-12-1udfiqqeh-lm8gcbhb3t7hl/7fb8c94975c27668d9ddcbbbf3c8015a5785bdea9c22edbb53520b0d400e2f1f/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
✖  fatal     GraphqlError: Resource not accessible by integration 
    at request.then.response (/node_modules/@octokit/graphql/lib/graphql.js:31:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

### FAILED alex-page/add-new-issue-project 22:00:43Z (15.89s)
```

let me see if I can try this on another org/repo combination and see if its just really specific to my current use case

**Comment by TheSalesOpsGuy** [comment]
(triple post...)

So it seems to work for me if I just use a `personal private` repo and project board but as soon as I move it back to my work repo it fails out with the same error message...

Edit: reading through some of your code I'm wondering if its because I'm the `owner` of my own repos/projects, but simply an admin for my org level ones

I'm going to spin up a new org and invite you to it so you can try to sandbox there as well: https://github.com/tsog-actions-tester-org

**Comment by alex-page** [comment]
Oh interesting lets try replicate that! Thanks for the heads up :)

**Comment by alex-page** [comment]
@TheSalesOpsGuy this should be fixed up now have a look at the docs and feel free to re open the issue if this solution doesn't work!
https://github.com/alex-page/add-new-issue-project#private-repositories

**Comment by ptfoote** [comment]
@alex-page - I didn't see a way to update the ReadMe without forking but for those who see this error after setting up their new secret ```GraphqlError: Resource protected by organization SAML enforcement. You must grant your personal token access to this organization``` will need to `Enable SSO` on the secret. Thanks for building this and your work to debug.

**Comment by alex-page** [comment]
@ptfoote I'll add this into the README now. I am not sure if there is a way I can allow you to do PR's without forks 🤔
